name: Generate ASCII Artwork

on:
    push

jobs: 
    ascii_job:
        runs-on: ubuntu-latest
        steps: 
        - name: Checkout Repo
          uses: actions/checkout@v4
    
        - name: list files
          run:  ls -ltra

        - name: execute shell script
          run: | 
            chmod +x ascii_script.sh
            ./ascii_script.sh
