name: Exploring variables and Secrets

on:
    schedule:
      - cron: "*/1 * * * *"
    # push

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Docker Build
              run: docker build -t docker.io/dockerusername/imageName:latest

            - name: Docker Login
              run: docker login --username=dockerUsername --password=s3curePaSsw0rd
            
            - name: Docker Publish
              run: docker push docker.io/dockerUsername/imageName:latest
    
    deploy:
        needs: docker
        runs-on: ubuntu-latest
        steps:
          - name: Docker run
            run: docker run -d -p 8080:80 docker.io/dockerUsername/imageName:latest
        
          - name: check files
            run: ls
 